version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    container_name: PgSQL-DB
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data
  
  cache:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-server
    image: go-server
    entrypoint: [/data/server]
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - cache
    env_file:
      - .env
    links:
      - cache
    volumes:
      - ./:/src
  
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-worker
    image: go-worker
    entrypoint: [/data/worker]
    restart: unless-stopped
    depends_on:
      - db
      - cache
    env_file:
      - .env
    links:
      - db
      - cache
    volumes:
      - ./:/src
  
volumes:
  db:
    driver: local
  cache:
    driver: local

networks:
  internal:
    driver: bridge
